name: Publish

on:
  release:
    types: [published]

jobs:
  publish-dockerhub:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile -t blocklist-updater

    - name: Tag image
      run: |
        docker tag blocklist-updater dmachard/blocklist-updater:${{ github.event.release.tag_name }}
        docker tag blocklist-updater dmachard/blocklist-updater:latest

    - name: Upload to DockerHub
      run: |
        docker login -u ${{ secrets.DOCKERHUB_LOGIN }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
        docker push dmachard/blocklist-updater:latest
        docker push dmachard/blocklist-updater:${{ github.event.release.tag_name }}